### PR TITLE
fix: carry PrepareQC lock across consecutive timeouts in voteTimeout

### LINKED ISSUE #1: Node system requirements
Hello. What are the system requirements for installing this node? In the documentation https://docs.seinetwork.io/nodes-and-validators/joining-testnets this column is empty.

### PR DESCRIPTION
**Pull request by wen-coding**
## Summary

- **Safety bug fix**: `voteTimeout` only attached `i.PrepareQC` (current view) to TimeoutVotes. Since `pushTimeoutQC` clears `i.PrepareQC` on view change, consecutive timeouts (e.g. offline leader) would lose the PrepareQC lock. This produced a TimeoutQC with no `latestPrepareQC`, allowing a later leader to propose a conflicting block instead of being forced to repropose — breaking the safety invariant (two CommitQCs possible at the same RoadIndex).
- **Fix**: If no PrepareQC was observed in the current view (`!pqc.IsPresent()`), `voteTimeout` now inherits the one from `i.TimeoutQC.LatestPrepareQC()`. The lock propagates through the TimeoutQC chain indefinitely until a CommitQC advances the RoadIndex.
- **No new state or messages**: the fix reads an existing field (`TimeoutQC.LatestPrepareQC()`) that was already persisted; no schema or protocol changes needed.

### Attack scenario (before fix)

1. View (M, 0): PrepareQC forms for P. CommitVotes sent. Timer fires → TimeoutQC(M,0) carries the PrepareQC.
2. View (M, 1): `pushTimeoutQC` clears `i.PrepareQC`. Leader is offline. Timer fires → TimeoutVotes carry **no** PrepareQC. TimeoutQC(M,1) has `latestPrepareQC = None`.
3. View (M, 2): No reproposal forced. Leader proposes conflicting P'. CommitQC for P' forms. Old CommitVotes from step 1 also form CommitQC for P. **Two CommitQCs at RoadIndex M.**

### Why fix #1 alone is sufficient (no lock check in pushProposal needed)

With the fix, every honest validator's TimeoutVote carries the inherited PrepareQC. Any quorum of 2f+1 timeout votes includes ≥ f+1 honest validators carrying it, so `NewTimeoutQC` always selects it. `FullProposal.Verify` already enforces that if `TimeoutQC.reproposal()` returns a proposal, the leader must repropose it — so conflicting proposals are rejected by all honest validators.

## Test plan

Tests exercise the real `State.pushTimeoutQC`, `State.pushPrepareQC`, and `State.voteTimeout` methods via `scope.Run` + `s.Run(ctx)` (no mirrored production logic):

- [x] `TestVoteTimeoutPrepareQC_BothNone` — both None → None
- [x] `TestVoteTimeoutPrepareQC_OnlyCurrentView` — current view PrepareQC, no TimeoutQC → uses current
- [x] `TestVoteTimeoutPrepareQC_InheritedFromTimeoutQC` — core safety test: None + inherited → uses inherited, chains through 3 consecutive timeouts
- [x] `TestVoteTimeoutPrepareQC_CurrentViewHigherThanInherited` — reproposal succeeds (both present, current higher) → uses current
- [x] `TestVoteTimeoutPrepareQC_CurrentViewPresentInheritedNone` — current present, TimeoutQC has no PrepareQC → uses current
- [x] `TestVoteTimeoutPrepareQC_PersistedRestart` — restart regression: persisted TimeoutQC survives restart, voteTimeout inherits PrepareQC from it
- [x] `TestNewTimeoutQC_MixedPrepareQCs` — quorum-intersection: single vote carries PrepareQC among None votes → selected and Verify passes
- [x] `TestNewTimeoutQC_AllNone` — all votes carry None → LatestPrepareQC is None, Verify passes
- [x] `TestTimeoutQCVerify_HighestPrepareQCSelected` — votes carry PrepareQCs at different views → highest selected, Verify passes
- [x] Verified test fails when fix is reverted (`InheritedFromTimeoutQC` catches the bug)
- [x] All existing consensus and types tests pass

### CODE REVIEW

File: sei-tendermint/internal/autobahn/consensus/inner.go [hunk 1]
```diff
@@ -155,7 +155,17 @@ func (s *State) voteTimeout(ctx context.Context, view types.View) error {
 		if i.View() != view || i.TimeoutVote.IsPresent() {
 			return nil
 		}
-		v := types.NewFullTimeoutVote(s.cfg.Key, view, i.PrepareQC)
+		// Attach the highest PrepareQC between the current view's and the one
+		// inherited from the TimeoutQC that justified entering this view.
+		// Without this, consecutive timeouts (e.g. offline leader) would lose
+		// the lock and allow a conflicting proposal to be committed.
+		pqc := i.PrepareQC
+		if tqc, ok := i.TimeoutQC.Get(); ok {
```
Comment (pompon0) [inline sei-tendermint/internal/autobahn/consensus/inner.go]: nit
```
if tqc,ok := i.TimeoutQC.Get(); ok && !pqc.IsPresent() {
  pqc = tqc.LastestPrepareQC
}
```

File: sei-tendermint/internal/autobahn/consensus/inner_test.go [hunk 2]
```diff
@@ -920,3 +920,151 @@ func TestPushTimeoutQCClearsStaleState(t *testing.T) {
...
+// attach the given PrepareQC.
+func makeTimeoutQC(keys []types.SecretKey, view types.View, pqc utils.Option[*types.PrepareQC]) *types.TimeoutQC {
+	votes := make([]*types.FullTimeoutVote, len(keys))
+	for i, k := range keys {
+		votes[i] = types.NewFullTimeoutVote(k, view, pqc)
+	}
+	return types.NewTimeoutQC(votes)
+}
+
+// simulatePushTimeoutQC mirrors the production pushTimeoutQC: keeps CommitQC
```
Comment (pompon0) [inline sei-tendermint/internal/autobahn/consensus/inner_test.go]: can you simulate it on State rather than inner, so that we don't have to "mirror" anything?

File: sei-tendermint/internal/autobahn/consensus/inner.go (hunk 1 above)
Comment (wen-coding) [reply sei-tendermint/internal/autobahn/consensus/inner.go]: done

File: sei-tendermint/internal/autobahn/consensus/inner_test.go (hunk 2 above)
Comment (wen-coding) [reply sei-tendermint/internal/autobahn/consensus/inner_test.go]: done

File: sei-tendermint/internal/autobahn/consensus/state_test.go [hunk 3]
```diff
@@ -0,0 +1,197 @@
...
+		PersistentStateDir: utils.None[string](),
+	}, dataState)
+	require.NoError(t, err)
+	return s
+}
+
+// startRunOutputs launches runOutputs in the background and returns
+// a context that is cancelled when the test finishes.
+func startRunOutputs(t *testing.T, s *State) context.Context {
+	ctx, cancel := context.WithCancel(t.Context())
```
Comment (pompon0) [inline sei-tendermint/internal/autobahn/consensus/state_test.go]: this doesn't make sense. t.Context() is always canceled when the test finishes.
Also, why not s.Run()? The fact that s.runOutputs is suffcient rn is an implementation detail that the test should not need to rely on.
Also the s.Run() output should be checked for (non-cancellation) error, so I'd recommend `scope.Run(func(){ s.SpawnBg(s.Run()) })`

Comment (wen-coding) [reply sei-tendermint/internal/autobahn/consensus/state_test.go]: changed

File: sei-tendermint/internal/autobahn/consensus/state_test.go [hunk 4]
```diff
@@ -0,0 +1,261 @@
...
+			return fmt.Errorf("PrepareQC should be present")
+		}
+		pqc, _ := gotPQC.Get()
+		if pqc.Proposal().View() != view1 {
+			return fmt.Errorf("expected PrepareQC at view %v, got %v", view1, pqc.Proposal().View())
+		}
+		return nil
+	})
+	require.NoError(t, err)
+}
```
Comment (masih) [inline sei-tendermint/internal/autobahn/consensus/state_test.go:261]: Not a blocker: It would be great to also add a test cases for 
* the exact quorum-intersection behavior in `NewTimeoutQC` plus `TimeoutQC.Verify`.
* the restart regression test with persisted `TimeoutQC` just to verify `voteTimeout` is carried over to prepare.

Comment (wen-coding) [reply sei-tendermint/internal/autobahn/consensus/state_test.go:261]: done
